### ISSUE TITLE
Any way to refresh the model?

### ISSUE THREAD

**Issue by enayetn** [kshaaban-/ionic-durationpicker#9]
Hello,

Thanks for building this widget! I am seeing an odd issue -- I've bound an object property to the idp-output attribute. However when my script changes that value, the duration does not change. I have to tap the duration picker open, and then hit cancel before it will refresh itself. 

Is there any way to manually trigger the picker to refresh?

**Comment by webdevius** [comment]
Hello enayetn

I have pushed a fix for the issue! Let me know if it works as expected.

**Comment by enayetn** [comment]
Nice! Works great, thanks 😀
